language: python
python:
  - "3.4"
sudo: false
install:
  - pip install catkin-pkg PyYAML rosdistro
  - pip install coverage flake8 flake8-docstrings flake8-import-order nose pep8 pyflakes
  # install empy for Python 3
  - git clone https://github.com/dirk-thomas/empy.git /tmp/empy
  - cd /tmp/empy
  - python setup.py install
  - cd -
script:
  - python setup.py nosetests -s --tests test
notifications:
  email: false
